apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-crm
  template:
    metadata:
      labels:
        app: demo-crm
    spec:
      containers:
        - name: demo-crm
          image: ghcr.io/esti563/demo-crm:10
          ports:
            - containerPort: 3000
