apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-crm
  template:
    metadata:
      labels:
        app: demo-crm
    spec:
      containers:
      - name: demo-crm
        image: ghcr.io/estiblass/demo-crm:build-20250623-0480000
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
