name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: demo-crm

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      run: |
        TAG="build-${{ github.run_id }}"
        IMAGE="$REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME:$TAG"
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV
        echo "Using image: $IMAGE"
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > kubeconfig.yaml
        export KUBECONFIG=$PWD/kubeconfig.yaml

    - name: Create image pull secret for GHCR
      run: |
        kubectl delete secret ghcr-secret --ignore-not-found
        kubectl create secret docker-registry ghcr-secret \
          --docker-server=ghcr.io \
          --docker-username=${{ github.actor }} \
          --docker-password=${{ secrets.GHCR_TOKEN }} \
          --docker-email=none@example.com

    - name: Deploy to Kubernetes
      run: |
        sed "s|IMAGE_PLACEHOLDER|${{ env.IMAGE }}|g" k8s/deployment.yaml > k8s/deployment.temp.yaml
        kubectl apply -f k8s/deployment.temp.yaml
        kubectl rollout status deployment/demo-crm --timeout=300s
